# Generated by Django 4.0.3 on 2024-04-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0004_group_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='active',
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2),
        ),
    ]
