# Generated by Django 4.0.3 on 2024-04-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
