# Generated by Django 4.0.3 on 2024-04-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
